### ISSUE TITLE
Standardize name

### ISSUE THREAD

**Issue by EnochPrime** [jay-oswald/ha-wican#3]
In most places this integration is referred to as `WiCan` except in hacs which uses the spelling `WiCAN`. 

According to the [website](https://www.meatpi.com/products/wican) the spelling should be `WiCAN`.

**Comment by jay-oswald** [comment]
Thanks @EnochPrime In my head it was `WiCan` so I was using that, then realised it was officially `WiCAN`. Defintly needs a cleanup, feel free to put in a PR to clean it up if you want, but its on my to do list

**Comment by EnochPrime** [comment]
> Thanks @EnochPrime In my head it was `WiCan` so I was using that, then realised it was officially `WiCAN`. Defintly needs a cleanup, feel free to put in a PR to clean it up if you want, but its on my to do list

How do you feel about the casing for the python package and classes?
There seems to be [debate](https://stackoverflow.com/questions/2853531/how-do-you-pep-8-name-a-class-whose-name-is-an-acronym) online about how the [PEP-8 standard](https://peps.python.org/pep-0008/#descriptive-naming-styles) applies. They standard states that `WiCAN` would be better than `WiCan` since CAN is an acronym.

**Comment by jay-oswald** [comment]
@EnochPrime I'm primarly a PHP and JS developer, this, and my other HA integration (which is even simpler than this already) is the only Python I've done, so I basically have no feelings around any Python standards etc.

However regardless of any standards at this point `WiCAN` is a product name, and treating the `CAN` as an acronym I just don't think applies, even if that's how it got its name. PR looks good, I have another version locally I haven't pushed up yet will merge this in before that to include it in the next release, assuming your happy enough with it to remove the draft flag.

In regards to standards and naming and stuff in general, I would defiantly want the whole code base cleaned up before a 1.x release, however at this stage I just want things working, have all MVP features working, tested, then we can do a full cleanup for a 1.x release, and then add linting action and stuff to enforce them going forward
